# .github/workflows/lint.yml
name: Lint & Type Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Deps
        run: pip install mypy ruff

      - name: Type Check
        run: mypy src/

      - name: Lint Check
        run: ruff src/
